version: '3.8' # Docker Compose sürümü, 3.8 genellikle iyidir
services:
  postgres_db: # Servisimizin adı (istediğiniz ismi verebilirsiniz)
    image: postgres:latest # Kullanılacak PostgreSQL Docker imajı
    container_name: repsy_postgres # Konteynerin adı
    environment:
      POSTGRES_DB: repsy_db # Oluşturulacak veritabanı adı
      POSTGRES_USER: repsy_user # Veritabanı kullanıcısı
      POSTGRES_PASSWORD: repsy_password # Veritabanı şifresi
    ports:
      - "5432:5432" # Bilgisayarınızdaki 5432 portunu konteynerdeki 5432 portuna bağlar
    volumes:
      - postgres_data:/var/lib/postgresql/data # Veritabanı verilerinin kalıcı olmasını sağlar

  minio:
    image: minio/minio
    container_name: repsy_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO konsol portu
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  repsy_api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
      - minio
    volumes:
      - ./storage:/storage # Yerel storage dizinini konteyner içindeki /storage dizinine bağla
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/repsy_db
      SPRING_DATASOURCE_USERNAME: repsy_user
      SPRING_DATASOURCE_PASSWORD: repsy_password
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: repsy-packages
      STORAGE_STRATEGY: file-system # object-storage or file-system

volumes:
  postgres_data: 
  minio_data: